# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dbda94c8567fa8c82305524167c618f8ff4a5aa6b5ad3235f7394ef1ee5d2f1be7c06ac3c7d12678260030e32afef6382a03dd4ead825b89d5e4e0ed9781d87

test:
  secret_key_base: ad788d8005c870f9b7e7bc5f349ff8210b1894ab8f39a17429690dc255abff2d3ca0efdcb52daa46633853f59fcd33b0906abe509f40983d860b8ee9be2ba051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
